# Generated by Django 3.2.3 on 2021-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='プレミアムユーザーかどうか'),
        ),
    ]
